### ISSUE TITLE
Suggestion: move menu to left sidebar

### ISSUE THREAD

**Issue by tiagoFlach** [Nokse22/inspector#3]
I think viewing this app would be much easier if it is displayed in the same way as gnome settings.

**Comment by Nokse22** [comment]
You are right, in fact I was actually already porting it to a different layout. When gnome 45 is released I will be updating the app since I am using widgets from Libadwaita 1.4.
The app will loo like this:

![Screenshot from 2023-08-15 17-41-18](https://github.com/Nokse22/inspector/assets/44558032/8d3c5de5-4c69-44ae-9b24-33d4af476c14)


![Screenshot from 2023-08-15 17-41-00](https://github.com/Nokse22/inspector/assets/44558032/59979437-9b2a-49e1-aed5-805fc84f4a2d)

![Screenshot from 2023-08-15 17-45-09](https://github.com/Nokse22/inspector/assets/44558032/afa2f1ee-d02c-4509-b210-d687ea6b7cf5)

**Comment by tiagoFlach** [comment]
Very nice work!!! 👏🏼
